/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicoRouteImport } from './routes/$servico'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos/index'
import { Route as SegmentosSegmentoRouteImport } from './routes/segmentos/$segmento'
import { Route as ServicosIndexRouteImport } from './routes/servicos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicoRoute = ServicoRouteImport.update({
  id: '/$servico',
  path: '/$servico',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/segmentos/',
  path: '/segmentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosSegmentoRoute = SegmentosSegmentoRouteImport.update({
  id: '/segmentos/$segmento',
  path: '/segmentos/$segmento',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$servico': typeof ServicoRoute
  '/segmentos/$segmento': typeof SegmentosSegmentoRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$servico': typeof ServicoRoute
  '/segmentos/$segmento': typeof SegmentosSegmentoRoute
  '/segmentos': typeof SegmentosIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$servico': typeof ServicoRoute
  '/segmentos/$segmento': typeof SegmentosSegmentoRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$servico' | '/segmentos/$segmento' | '/segmentos/' | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$servico' | '/segmentos/$segmento' | '/segmentos' | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/$servico'
    | '/segmentos/$segmento'
    | '/segmentos/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicoRoute: typeof ServicoRoute
  SegmentosSegmentoRoute: typeof SegmentosSegmentoRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$servico': {
      id: '/$servico'
      path: '/$servico'
      fullPath: '/$servico'
      preLoaderRoute: typeof ServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/segmentos'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/$segmento': {
      id: '/segmentos/$segmento'
      path: '/segmentos/$segmento'
      fullPath: '/segmentos/$segmento'
      preLoaderRoute: typeof SegmentosSegmentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicoRoute: ServicoRoute,
  SegmentosSegmentoRoute: SegmentosSegmentoRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
